<a href="https://colab.research.google.com/github/Mr22XX/AI_Model/blob/main/TwoLayerNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler

# Dataset: [Jam Bangun, Jarak ke Kantor] → [Terlambat (1) / Tidak (0)]
X_data = [[6.5, 2], [7.0, 5], [6.0, 1], [7.5, 8], [5.5, 1], [8.0, 10], [6.8, 4]]
y_data = [[0], [1], [0], [1], [0], [1], [1]]

# Normalisasi data agar lebih stabil
scaler = StandardScaler()
X = torch.tensor(scaler.fit_transform(X_data), dtype=torch.float32)
y = torch.tensor(y_data, dtype=torch.float32)

# Neural Network dengan 2 Layer
class OfficeLateNN(nn.Module):
    def __init__(self):
        super(OfficeLateNN, self).__init__()
        self.hidden = nn.Linear(2, 5)  # 2 input -> 5 hidden neurons
        self.output = nn.Linear(5, 1)  # 5 hidden -> 1 output neuron
        self.activation = nn.ReLU()    # ReLU untuk hidden layer
        self.sigmoid = nn.Sigmoid()    # Sigmoid untuk output probabilitas

    def forward(self, x):
        x = self.activation(self.hidden(x))
        x = self.sigmoid(self.output(x))
        return x

# Inisialisasi model
model = OfficeLateNN()
criterion = nn.BCELoss()  # Binary Cross Entropy untuk klasifikasi
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training model
num_epochs = 2000
for epoch in range(num_epochs):
    optimizer.zero_grad()
    outputs = model(X)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()

    if (epoch+1) % 500 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

# Evaluasi model
with torch.no_grad():
    prediksi = model(X)
    prediksi_label = (prediksi.detach().numpy() > 0.5).astype(int)  # Perbaikan disini
    print("\nPrediksi Probabilitas Keterlambatan:\n", prediksi.detach().numpy())  # Perbaikan disini
    print("\nPrediksi Label (0: Tepat Waktu, 1: Terlambat):\n", prediksi_label)

# Contoh Prediksi Baru
data_baru = torch.tensor(scaler.transform([[6.3, 3], [7.8, 7]]), dtype=torch.float32)
prediksi_baru = model(data_baru)

# Perbaikan disini
print("\nPrediksi Probabilitas untuk Data Baru:\n", prediksi_baru.detach().numpy())
print("\nPrediksi Label untuk Data Baru:\n", (prediksi_baru.detach().numpy() > 0.5).astype(int))



Epoch [500/2000], Loss: 0.0036
Epoch [1000/2000], Loss: 0.0009
Epoch [1500/2000], Loss: 0.0004
Epoch [2000/2000], Loss: 0.0002

Prediksi Probabilitas Keterlambatan:
 [[5.42093243e-04]
 [9.99921679e-01]
 [1.02495274e-08]
 [9.99999881e-01]
 [3.71941471e-11]
 [1.00000000e+00]
 [9.99203503e-01]]

Prediksi Label (0: Tepat Waktu, 1: Terlambat):
 [[0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]]

Prediksi Probabilitas untuk Data Baru:
 [[0.00385731]
 [0.9999999 ]]

Prediksi Label untuk Data Baru:
 [[0]
 [1]]
